# Persistence
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Authentication (No anonymous access)
allow_anonymous false
password_file /mosquitto/config/passwd

# Port 1883 (Standard MQTT)
listener 1883

# Port 8883 (MQTTS / TLS)
listener 8883
certfile /mosquitto/certs/server.crt
cafile /mosquitto/certs/ca.crt
keyfile /mosquitto/certs/server.key

# Port 9001 (WebSocket)
listener 9001
protocol websockets
